// ============================================================
// Template Generator Module
// Produces ready-to-deploy proxy template files for tenants
// in PHP, Node.js (Express), and Python (Flask) per business type.
// ============================================================

import type { BusinessType } from './connector-cache.js';

export type TemplateLanguage = 'php' | 'nodejs' | 'python';

// Actions defined per business type (includes ping for all)
const BUSINESS_TYPE_ACTIONS: Record<BusinessType, string[]> = {
  ecommerce: ['ping', 'search_products', 'get_product_detail', 'list_categories', 'insert_order', 'list_stores'],
  appointments: ['ping', 'check_availability', 'list_services', 'book_appointment', 'cancel_appointment'],
  restaurant: ['ping', 'get_menu', 'check_item_availability', 'place_order'],
  services: ['ping', 'search', 'get_detail', 'submit_inquiry'],
  general: ['ping', 'search'],
};

/**
 * Generates a proxy template file for the given language and business type.
 * Optionally pre-fills the connector token.
 *
 * @param language - 'php' | 'nodejs' | 'python'
 * @param businessType - One of the defined business types
 * @param connectorToken - Optional: pre-fill the CONNECTOR_TOKEN placeholder
 * @returns Full file content as a string, ready to save and deploy
 */
export function generateTemplate(
  language: TemplateLanguage,
  businessType: BusinessType,
  connectorToken?: string
): string {
  const token = connectorToken ?? 'YOUR_CONNECTOR_TOKEN_HERE';

  switch (language) {
    case 'php':
      return generatePhpTemplate(businessType, token);
    case 'nodejs':
      return generateNodejsTemplate(businessType, token);
    case 'python':
      return generatePythonTemplate(businessType, token);
    default:
      throw new Error(`Unsupported template language: ${language}`);
  }
}

// ============================================================
// PHP Template Generator (uses PDO)
// ============================================================

function generatePhpTemplate(businessType: BusinessType, token: string): string {
  const actions = BUSINESS_TYPE_ACTIONS[businessType];

  const actionHandlers = actions.map(action => generatePhpActionHandler(action, businessType)).join('\n\n');

  return `<?php
/**
 * Eteba Chat Proxy — ${businessType} connector
 * Generated by Eteba Chat Template Generator
 *
 * Deploy this file on your server and configure the constants below.
 * Requires PHP 8.0+ and PDO with your database driver.
 *
 * Supported actions: ${actions.join(', ')}
 */

// ─── Configuration ───────────────────────────────────────────
define('CONNECTOR_TOKEN', '${token}');
define('BUSINESS_TYPE', '${businessType}');

// Database connection settings — update these for your environment
define('DB_DSN',      'mysql:host=localhost;dbname=your_database;charset=utf8mb4');
define('DB_USER',     'your_db_user');
define('DB_PASSWORD', 'your_db_password');

// ─── CORS Headers ────────────────────────────────────────────
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: POST, OPTIONS');
header('Access-Control-Allow-Headers: Content-Type, X-Chat-Token');
header('Content-Type: application/json; charset=utf-8');

if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    http_response_code(204);
    exit;
}

// ─── Token Validation (constant-time comparison) ─────────────
$incomingToken = $_SERVER['HTTP_X_CHAT_TOKEN'] ?? '';
if (!hash_equals(CONNECTOR_TOKEN, $incomingToken)) {
    http_response_code(401);
    echo json_encode(['error' => 'unauthorized']);
    exit;
}

// ─── Parse Request Body ──────────────────────────────────────
$raw = file_get_contents('php://input');
$body = json_decode($raw, true);
if (json_last_error() !== JSON_ERROR_NONE || !is_array($body)) {
    http_response_code(400);
    echo json_encode(['error' => 'invalid_json']);
    exit;
}

$action = $body['action'] ?? '';
$startTime = microtime(true);

// ─── Database Connection (PDO) ───────────────────────────────
try {
    $pdo = new PDO(DB_DSN, DB_USER, DB_PASSWORD, [
        PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
        PDO::ATTR_EMULATE_PREPARES   => false,
    ]);
} catch (PDOException $e) {
    http_response_code(500);
    echo json_encode(['error' => 'database_unavailable']);
    exit;
}

// ─── Action Dispatch ─────────────────────────────────────────
function sendResponse(mixed $data, string $action, float $startTime): void {
    $execMs = (int) round((microtime(true) - $startTime) * 1000);
    echo json_encode([
        'data' => $data,
        'meta' => [
            'timestamp'        => date('c'),
            'action'           => $action,
            'execution_time_ms'=> $execMs,
        ],
    ]);
    exit;
}

switch ($action) {
${actionHandlers}

    default:
        http_response_code(400);
        echo json_encode(['error' => 'unknown_action', 'action' => $action]);
        exit;
}
`;
}

// ============================================================
// PHP Action Handler Helper
// ============================================================

function generatePhpActionHandler(action: string, _businessType: BusinessType): string {
  switch (action) {
    case 'ping':
      return `    case 'ping':
        sendResponse(['status' => 'ok', 'business_type' => BUSINESS_TYPE, 'version' => '1.0'], $action, $startTime);`;
    case 'search_products':
      return `    case 'search_products':
        // TODO: query your products table
        // $term = $body['term'] ?? ''; $limit = min((int)($body['limit'] ?? 10), 50);
        sendResponse(['products' => []], $action, $startTime);`;
    case 'get_product_detail':
      return `    case 'get_product_detail':
        // TODO: fetch product by $body['id']
        sendResponse(['product' => null], $action, $startTime);`;
    case 'list_categories':
      return `    case 'list_categories':
        // TODO: fetch all categories
        sendResponse(['categories' => []], $action, $startTime);`;
    case 'insert_order':
      return `    case 'insert_order':
        // TODO: insert order with $body['product_id'], ['customer_name'], ['customer_phone'], ['delivery_city']
        sendResponse(['order_id' => null, 'status' => 'received'], $action, $startTime);`;
    case 'list_stores':
      return `    case 'list_stores':
        // TODO: fetch all stores
        sendResponse(['stores' => []], $action, $startTime);`;
    case 'check_availability':
      return `    case 'check_availability':
        // TODO: check availability for $body['date'], optional $body['service_type']
        sendResponse(['date' => $body['date'] ?? '', 'time_slots' => []], $action, $startTime);`;
    case 'list_services':
      return `    case 'list_services':
        // TODO: fetch services list
        sendResponse(['services' => []], $action, $startTime);`;
    case 'book_appointment':
      return `    case 'book_appointment':
        // TODO: book appointment with $body['service_id'], ['client_name'], etc.
        sendResponse(['appointment_id' => null, 'status' => 'booked'], $action, $startTime);`;
    case 'cancel_appointment':
      return `    case 'cancel_appointment':
        // TODO: cancel appointment $body['appointment_id']
        sendResponse(['status' => 'cancelled'], $action, $startTime);`;
    case 'get_menu':
      return `    case 'get_menu':
        // TODO: fetch menu, optional $body['category']
        sendResponse(['items' => []], $action, $startTime);`;
    case 'check_item_availability':
      return `    case 'check_item_availability':
        // TODO: check item $body['item_id']
        sendResponse(['available' => true], $action, $startTime);`;
    case 'place_order':
      return `    case 'place_order':
        // TODO: place order with $body['items'], ['customer_name'], ['customer_phone'], etc.
        sendResponse(['order_id' => null, 'status' => 'received'], $action, $startTime);`;
    case 'search':
      return `    case 'search':
        // TODO: search services with $body['term'], $body['limit']
        sendResponse(['results' => []], $action, $startTime);`;
    case 'get_detail':
      return `    case 'get_detail':
        // TODO: fetch detail for $body['id']
        sendResponse(['detail' => null], $action, $startTime);`;
    case 'submit_inquiry':
      return `    case 'submit_inquiry':
        // TODO: submit inquiry with $body['service_id'], ['client_name'], etc.
        sendResponse(['status' => 'received'], $action, $startTime);`;
    default:
      return `    case '${action}':
        // TODO: implement ${action}
        sendResponse([], $action, $startTime);`;
  }
}

// ============================================================
// Node.js (Express) Template Generator
// ============================================================

function generateNodejsTemplate(businessType: BusinessType, token: string): string {
  const actions = BUSINESS_TYPE_ACTIONS[businessType];

  const actionCases = actions.map(action => {
    if (action === 'ping') {
      return `    case 'ping':
      return res.json({ data: { status: 'ok', business_type: BUSINESS_TYPE, version: '1.0' }, meta });`;
    }
    return `    case '${action}':
      // TODO: implement ${action} — query your database here
      return res.json({ data: {}, meta });`;
  }).join('\n\n');

  return `/**
 * Eteba Chat Proxy — ${businessType} connector (Node.js / Express)
 * Generated by Eteba Chat Template Generator
 *
 * Supported actions: ${actions.join(', ')}
 */

const express = require('express');
const cors = require('cors');

const app = express();
const PORT = process.env.PORT || 3000;

// ─── Configuration ───────────────────────────────────────────
const CONNECTOR_TOKEN = '${token}';
const BUSINESS_TYPE = '${businessType}';

// ─── CORS & Body Parsing ─────────────────────────────────────
app.use(cors({ methods: ['POST', 'OPTIONS'] }));
app.use(express.json({ limit: '64kb' }));

// ─── Token Validation Middleware ─────────────────────────────
function validateToken(req, res, next) {
  const incoming = req.headers['x-chat-token'] ?? '';
  // Constant-time comparison to prevent timing attacks
  const expected = Buffer.from(CONNECTOR_TOKEN);
  const received = Buffer.from(incoming.padEnd(CONNECTOR_TOKEN.length));
  if (expected.length !== received.length || !require('crypto').timingSafeEqual(expected, received)) {
    return res.status(401).json({ error: 'unauthorized' });
  }
  next();
}

// ─── Main Route ──────────────────────────────────────────────
app.post('/', validateToken, (req, res) => {
  const { action, ...params } = req.body;
  const startTime = Date.now();

  const meta = {
    timestamp: new Date().toISOString(),
    action,
    execution_time_ms: 0, // updated before each response
  };

  const respond = (data) => {
    meta.execution_time_ms = Date.now() - startTime;
    return res.json({ data, meta });
  };

  switch (action) {
${actionCases}

    default:
      return res.status(400).json({ error: 'unknown_action', action });
  }
});

app.listen(PORT, () => console.log(\`Eteba Chat proxy running on port \${PORT}\`));
`;
}

// ============================================================
// Python (Flask) Template Generator
// ============================================================

function generatePythonTemplate(businessType: BusinessType, token: string): string {
  const actions = BUSINESS_TYPE_ACTIONS[businessType];

  const actionBranches = actions.map((action, i) => {
    const prefix = i === 0 ? '    if' : '    elif';
    if (action === 'ping') {
      return `${prefix} action == 'ping':
        data = {'status': 'ok', 'business_type': BUSINESS_TYPE, 'version': '1.0'}`;
    }
    return `${prefix} action == '${action}':
        # TODO: implement ${action} — query your database here
        data = {}`;
  }).join('\n') + `
    else:
        return jsonify({'error': 'unknown_action', 'action': action}), 400`;

  return `"""
Eteba Chat Proxy — ${businessType} connector (Python / Flask)
Generated by Eteba Chat Template Generator

Supported actions: ${actions.join(', ')}

Install: pip install flask flask-cors
Run:     flask run
"""

import hashlib
import hmac
import time
from datetime import datetime, timezone
from flask import Flask, request, jsonify
from flask_cors import CORS

app = Flask(__name__)
CORS(app, methods=['POST', 'OPTIONS'])

# ─── Configuration ───────────────────────────────────────────
CONNECTOR_TOKEN = '${token}'
BUSINESS_TYPE = '${businessType}'

# ─── Token Validation Helper ─────────────────────────────────
def validate_token(incoming: str) -> bool:
    """Constant-time comparison to prevent timing attacks."""
    return hmac.compare_digest(CONNECTOR_TOKEN, incoming)

# ─── Main Endpoint ───────────────────────────────────────────
@app.route('/', methods=['POST'])
def proxy():
    incoming_token = request.headers.get('X-Chat-Token', '')
    if not validate_token(incoming_token):
        return jsonify({'error': 'unauthorized'}), 401

    try:
        body = request.get_json(force=True, silent=False)
    except Exception:
        return jsonify({'error': 'invalid_json'}), 400

    if body is None:
        return jsonify({'error': 'invalid_json'}), 400

    action = body.get('action', '')
    start_ms = int(time.time() * 1000)

${actionBranches}

    exec_ms = int(time.time() * 1000) - start_ms
    return jsonify({
        'data': data,
        'meta': {
            'timestamp': datetime.now(timezone.utc).isoformat(),
            'action': action,
            'execution_time_ms': exec_ms,
        },
    })

if __name__ == '__main__':
    app.run(port=3000, debug=False)
`;
}
